export const controls = [
    { "name": "Create User", "route": "/create-user", "type": "admin" },
    { "name": "Edit User", "route": "/edit-user", "type": "admin" },
    { "name": "Delete User", "route": "/delete-user", "type": "admin" },
    { "name": "View Reports", "route": "/view-reports", "type": "agent" },
    { "name": "Manage Projects", "route": "/manage-projects", "type": "admin" },
    { "name": "View Tasks", "route": "/view-tasks", "type": "agent" },
    { "name": "Submit Timesheet", "route": "/submit-timesheet", "type": "agent" },
    { "name": "Approve Leave", "route": "/approve-leave", "type": "admin" },
    { "name": "Manage Shifts", "route": "/manage-shifts", "type": "admin" },
    { "name": "View Code Repositories", "route": "/view-code-repositories", "type": "agent" },
    { "name": "Commit Changes", "route": "/commit-changes", "type": "agent" },
    { "name": "Run Tests", "route": "/run-tests", "type": "agent" },
    { "name": "Report Bugs", "route": "/report-bugs", "type": "agent" },
    { "name": "Create Designs", "route": "/create-designs", "type": "agent" },
    { "name": "Review Designs", "route": "/review-designs", "type": "agent" },
    { "name": "Answer Inquiries", "route": "/answer-inquiries", "type": "agent" },
    { "name": "Resolve Complaints", "route": "/resolve-complaints", "type": "agent" },
    { "name": "Approve Expenses", "route": "/approve-expenses", "type": "admin" },
    { "name": "Generate Financial Reports", "route": "/generate-financial-reports", "type": "admin" },
    { "name": "Recruit Employees", "route": "/recruit-employees", "type": "admin" },
    { "name": "Handle Employee Benefits", "route": "/handle-employee-benefits", "type": "admin" },
    { "name": "Manage Inventory", "route": "/manage-inventory", "type": "admin" },
    { "name": "Order Supplies", "route": "/order-supplies", "type": "admin" },
    { "name": "Track Shipments", "route": "/track-shipments", "type": "agent" },
    { "name": "Approve Purchase Orders", "route": "/approve-purchase-orders", "type": "admin" },
    { "name": "Manage Vendors", "route": "/manage-vendors", "type": "admin" },
    { "name": "Create Invoices", "route": "/create-invoices", "type": "agent" },
    { "name": "Process Payments", "route": "/process-payments", "type": "admin" },
    { "name": "Manage Accounts", "route": "/manage-accounts", "type": "admin" },
    { "name": "View Analytics", "route": "/view-analytics", "type": "agent" },
    { "name": "Create Campaigns", "route": "/create-campaigns", "type": "agent" },
    { "name": "Monitor Social Media", "route": "/monitor-social-media", "type": "agent" },
    { "name": "Manage Customer Relationships", "route": "/manage-customer-relationships", "type": "agent" },
    { "name": "Generate Leads", "route": "/generate-leads", "type": "agent" },
    { "name": "Schedule Appointments", "route": "/schedule-appointments", "type": "agent" },
    { "name": "Manage Calendar", "route": "/manage-calendar", "type": "agent" },
    { "name": "Book Meeting Rooms", "route": "/book-meeting-rooms", "type": "agent" },
    { "name": "View Medical Records", "route": "/view-medical-records", "type": "admin" },
    { "name": "Prescribe Medication", "route": "/prescribe-medication", "type": "admin" },
    { "name": "Schedule Appointments", "route": "/schedule-appointments", "type": "agent" },
    { "name": "Manage Patient Data", "route": "/manage-patient-data", "type": "admin" },
    { "name": "Conduct Surveys", "route": "/conduct-surveys", "type": "agent" },
    { "name": "Analyze Survey Results", "route": "/analyze-survey-results", "type": "agent" },
    { "name": "Manage Training Programs", "route": "/manage-training-programs", "type": "admin" },
    { "name": "Assign Learning Modules", "route": "/assign-learning-modules", "type": "admin" },
    { "name": "View Performance Reviews", "route": "/view-performance-reviews", "type": "admin" },
    { "name": "Conduct Performance Appraisals", "route": "/conduct-performance-appraisals", "type": "admin" },
    { "name": "Manage Security Protocols", "route": "/manage-security-protocols", "type": "admin" },
    { "name": "Monitor Network Traffic", "route": "/monitor-network-traffic", "type": "admin" },
    { "name": "Audit System Logs", "route": "/audit-system-logs", "type": "admin" },
    { "name": "Access Control Settings", "route": "/access-control-settings", "type": "admin" }
];
