export const tags = [
    { "id": 1, "tag": "name", "qPlaceholderText": "Name", "qType": "Static" },
    { "id": 2, "tag": "age", "qPlaceholderText": "What is your Age", "qType": "Dynamic" },
    { "id": 3, "tag": "category", "qPlaceholderText": "Category", "qType": "Static2" },
    { "id": 4, "tag": "email", "qPlaceholderText": "Email Address", "qType": "Static" },
    { "id": 5, "tag": "phone", "qPlaceholderText": "Phone Number", "qType": "Dynamic" },
    { "id": 6, "tag": "address", "qPlaceholderText": "Home Address", "qType": "Static2" },
    { "id": 7, "tag": "gender", "qPlaceholderText": "What is your Gender", "qType": "Dynamic" },
    { "id": 8, "tag": "dob", "qPlaceholderText": "Date of Birth", "qType": "Static" },
    { "id": 9, "tag": "country", "qPlaceholderText": "Country of Residence", "qType": "Static2" },
    { "id": 10, "tag": "state", "qPlaceholderText": "State/Province", "qType": "Dynamic" },
    { "id": 11, "tag": "city", "qPlaceholderText": "City", "qType": "Static" },
    { "id": 12, "tag": "zipcode", "qPlaceholderText": "ZIP/Postal Code", "qType": "Static2" },
    { "id": 13, "tag": "occupation", "qPlaceholderText": "Occupation", "qType": "Dynamic" },
    { "id": 14, "tag": "company", "qPlaceholderText": "Company Name", "qType": "Static" },
    { "id": 15, "tag": "education", "qPlaceholderText": "Highest Level of Education", "qType": "Static2" },
    { "id": 16, "tag": "maritalStatus", "qPlaceholderText": "Marital Status", "qType": "Dynamic" },
    { "id": 17, "tag": "children", "qPlaceholderText": "Number of Children", "qType": "Static" },
    { "id": 18, "tag": "income", "qPlaceholderText": "Annual Income", "qType": "Static2" },
    { "id": 19, "tag": "languages", "qPlaceholderText": "Languages Spoken", "qType": "Dynamic" },
    { "id": 20, "tag": "hobbies", "qPlaceholderText": "Hobbies/Interests", "qType": "Static" },
    { "id": 21, "tag": "pets", "qPlaceholderText": "Do you have pets?", "qType": "Static2" },
    { "id": 22, "tag": "vehicle", "qPlaceholderText": "Do you own a vehicle?", "qType": "Dynamic" },
    { "id": 23, "tag": "internet", "qPlaceholderText": "Do you have internet access?", "qType": "Static" },
    { "id": 24, "tag": "smoking", "qPlaceholderText": "Do you smoke?", "qType": "Static2" },
    { "id": 25, "tag": "alcohol", "qPlaceholderText": "Do you consume alcohol?", "qType": "Dynamic" },
    { "id": 26, "tag": "exercise", "qPlaceholderText": "Do you exercise regularly?", "qType": "Static" },
    { "id": 27, "tag": "diet", "qPlaceholderText": "Do you follow a specific diet?", "qType": "Static2" },
    { "id": 28, "tag": "travel", "qPlaceholderText": "Do you travel frequently?", "qType": "Dynamic" },
    { "id": 29, "tag": "reading", "qPlaceholderText": "Do you enjoy reading?", "qType": "Static" },
    { "id": 30, "tag": "movies", "qPlaceholderText": "Do you like watching movies?", "qType": "Static2" },
    { "id": 31, "tag": "music", "qPlaceholderText": "Do you enjoy listening to music?", "qType": "Dynamic" },
    { "id": 32, "tag": "sports", "qPlaceholderText": "Do you play any sports?", "qType": "Static" },
    { "id": 33, "tag": "volunteer", "qPlaceholderText": "Do you volunteer?", "qType": "Static2" },
    { "id": 34, "tag": "socialMedia", "qPlaceholderText": "Are you active on social media?", "qType": "Dynamic" },
    { "id": 35, "tag": "gaming", "qPlaceholderText": "Do you play video games?", "qType": "Static" },
    { "id": 36, "tag": "shopping", "qPlaceholderText": "Do you enjoy shopping?", "qType": "Static2" },
    { "id": 37, "tag": "cooking", "qPlaceholderText": "Do you like cooking?", "qType": "Dynamic" },
    { "id": 38, "tag": "gardening", "qPlaceholderText": "Do you enjoy gardening?", "qType": "Static" },
    { "id": 39, "tag": "technology", "qPlaceholderText": "Are you interested in technology?", "qType": "Static2" },
    { "id": 40, "tag": "news", "qPlaceholderText": "Do you follow the news?", "qType": "Dynamic" },
    { "id": 41, "tag": "environment", "qPlaceholderText": "Are you concerned about the environment?", "qType": "Static" },
    { "id": 42, "tag": "politics", "qPlaceholderText": "Are you interested in politics?", "qType": "Static2" },
    { "id": 43, "tag": "religion", "qPlaceholderText": "Do you practice a religion?", "qType": "Dynamic" },
    { "id": 44, "tag": "health", "qPlaceholderText": "Do you have any health conditions?", "qType": "Static" },
    { "id": 45, "tag": "insurance", "qPlaceholderText": "Do you have health insurance?", "qType": "Static2" },
    { "id": 46, "tag": "investments", "qPlaceholderText": "Do you have any investments?", "qType": "Dynamic" },
    { "id": 47, "tag": "retirement", "qPlaceholderText": "Are you planning for retirement?", "qType": "Static" },
    { "id": 48, "tag": "housing", "qPlaceholderText": "Do you own or rent your home?", "qType": "Static2" },
    { "id": 49, "tag": "mortgage", "qPlaceholderText": "Do you have a mortgage?", "qType": "Dynamic" },
    { "id": 50, "tag": "creditCard", "qPlaceholderText": "Do you use credit cards?", "qType": "Static" }
]
